### ISSUE TITLE
Something wrong when i try pasting "app-with-list-view.js" to "app.js".

### ISSUE THREAD

**Issue by sacrelee** [nativescript-vue/nativescript-vue-template#7]
The app was freezen at startup page and get a error log: "JS ERROR TypeError: undefined is not an object (evaluating 'this.$templates.getKeyedTemplates')".

Could you help me? thanks.

**Comment by rigor789** [comment]
Hi, I have updated this template now, the sample you were trying was not updated for the new ListView syntax, but if you are still interested in that specific sample, it is available in the main repository here: https://github.com/nativescript-vue/nativescript-vue/blob/master/samples/app/app-with-list-view.js
